Repository clicepfl/website, pull requests merged in 2023-08, with the labels that each got.

#38 build: add nextjs app to devcontainer
  .devcontainer/docker-compose.yaml
  app/.devcontainer/Dockerfile
  app/.devcontainer/devcontainer.json
Labels: build

#26 feat: add strapi content type structure for CLIC models
  strapi/src/api/association/content-types/association/schema.json
  strapi/src/api/association/controllers/association.ts
  strapi/src/api/association/routes/association.ts
  strapi/src/api/association/services/association.ts
  strapi/src/api/commission/content-types/commission/schema.json
  strapi/src/api/commission/controllers/commission.ts
  strapi/src/api/commission/routes/commission.ts
  strapi/src/api/commission/services/commission.ts
  strapi/src/api/event/content-types/event/schema.json
  strapi/src/api/event/controllers/event.ts
  strapi/src/api/event/routes/event.ts
  strapi/src/api/event/services/event.ts
  strapi/src/api/member/content-types/member/schema.json
  strapi/src/api/member/controllers/member.ts
  strapi/src/api/member/routes/member.ts
  strapi/src/api/member/services/member.ts
  strapi/src/api/news/content-types/news/schema.json
  strapi/src/api/news/controllers/news.ts
  strapi/src/api/news/routes/news.ts
  strapi/src/api/news/services/news.ts
  strapi/src/api/partner/content-types/partner/schema.json
  strapi/src/api/partner/controllers/partner.ts
  strapi/src/api/partner/routes/partner.ts
  strapi/src/api/partner/services/partner.ts
  strapi/src/api/pole/content-types/pole/schema.json
  strapi/src/api/pole/controllers/pole.ts
  strapi/src/api/pole/routes/pole.ts
  strapi/src/api/pole/services/pole.ts
  strapi/src/api/social-link/content-types/social-link/schema.json
  strapi/src/api/social-link/controllers/social-link.ts
  strapi/src/api/social-link/routes/social-link.ts
  strapi/src/api/social-link/services/social-link.ts
Labels: feature

#22 chore: integrate development docker stack with vscode
  .devcontainer/docker-compose.yaml
  .vscode/settings.json
  .vscode/tasks.json
  strapi/.devcontainer/devcontainer.json
Labels: build

#39 chore: add development reverse proxy
  .devcontainer/docker-compose.yaml
  app/package-lock.json
  caddy/Caddyfile.dev
  strapi/.env.example
  strapi/config/middlewares.ts
  strapi/config/server.ts
  strapi/src/middlewares/admin-redirect.ts
Labels: build

#33 build: add docker build in actions
  .github/workflows/docker-build.yml
  .vscode/settings.json
  app/.dockerignore
  app/.gitignore
  app/Dockerfile
  app/package-lock.json
  app/package.json
  app/public/thirteen.svg
  app/src/pages/index.tsx
  app/src/styles/Home.module.css
  app/src/styles/globals.css
  app/tailwind.config.js
  app/tsconfig.json
  package-lock.json
  strapi/.dockerignore
  strapi/Dockerfile
  strapi/package-lock.json
  strapi/package.json
Labels: build, ci, devops
